source = configs/aesthetics.conf
source = configs/autostart.conf
source = configs/environment.conf
source = configs/input-rules.conf
source = configs/key-bindings.conf
source = configs/monitors.conf
source = configs/variables.conf
source = configs/windows-rules.conf
source = configs/workspaces.conf