# wallpaper {
#     monitor = DP-2
#     path = /home/espadia/.config/hypr/wallpaper/stairs.png
#     fit_mode = cover
# }

# wallpaper {
#     monitor = HDMI-A-2
#     path = /home/espadia/.config/hypr/wallpaper/stairs.png
#     fit_mode = cover
# }

# splash = false