music_directory     "/home/espadia/music/"
playlist_directory  "/home/espadia/music/playlists"
db_file             "/home/espadia/.config/mpd/database"
log_file            "/home/espadia/.config/mpd/log"
pid_file            "/home/espadia/.config/mpd/pid"
state_file          "/home/espadia/.config/mpd/state"

auto_update     "yes"
bind_to_address "localhost"
port            "6600"
restore_paused         "yes"
max_output_buffer_size "16384"

audio_output {
    type "pipewire"
    name "pipewire output"
}

audio_output {
    type   "fifo"
    name   "Visualizer feed"
    path   "/tmp/mpd.fifo"
    format "44100:16:2"
}