#window manager beahavior layout gaps blablabla
general {
    # Inner and Outer gaps between windows.
    gaps_in = 4  
    gaps_out = 8

    # I prefer a thin border
    border_size = 4

    # Border colors.
    col.active_border = rgb(851200)
    col.inactive_border = rgb(964A41)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    layout = dwindle

    # READ https://wiki.hyprland.org/Configuring/Tearing/ BEFORE TURNING ON!
    allow_tearing = false
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

#configures the master layout behavior
master {
    new_status = master
}

#dwindle layout
dwindle {
    pseudotile = true
    preserve_split = true
}


animations {
    bezier = fluent_decel, 0, 0.2, 0.4, 1
    bezier = easeOutCirc, 0, 0.55, 0.45, 1
    bezier = easeOutCubic, 0.33, 1, 0.68, 1
    bezier = easeinoutsine, 0.37, 0, 0.63, 1

    # Windows
    animation = windowsIn, 1, 1.5, easeinoutsine, popin 60% # window open
    animation = windowsOut, 1, 1.5, easeOutCubic, popin 60% # window close.
    animation = windowsMove, 1, 1.5, easeinoutsine, slide # everything in between, moving, dragging, resizing.

    # Fading
    animation = fade, 1, 2.5, fluent_decel

	animation = fadeLayersIn, 0
    animation = border, 0


	# Layers
	animation = layers, 1, 1.5, easeinoutsine, popin

    # Workspaces
    #animation = workspaces, 1, 3, fluent_decel, slidefade 30% # styles: slide, slidevert, fade, slidefade, slidefadevert
    animation = workspaces, 1, 3, fluent_decel, slidefadevert 30% # styles: slide, slidevert, fade, slidefade, slidefadevert

	animation = specialWorkspace, 1, 2, fluent_decel, slidefade 10%
}

decoration {
    rounding = 6

    # I want transparancy to not change, since we have the colored border.
    active_opacity = 0.999
    inactive_opacity = 0.85

    # Window Shadow
    shadow:enabled = true
    shadow:range = 25
    shadow:render_power = 5
    shadow:color = rgba(168, 0, 0, 0.49)

    # Transparent Window Blur
    blur:enabled = true

    blur:new_optimizations = true
    blur:size = 2
    blur:passes = 3
    blur:vibrancy = 0.1696
}