# Startup programs, these are mine, most likely you'll have these as well.
exec-once = awww-daemon
exec-once = waypaper --restore
exec-once = waybar
# exec-once = $HOME/.config/eww/scripts/start.sh
exec-once = zen-browser &
exec-once = discord
