# Cursor settings
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# GTK Apps
env = GTK_THEME,Razor-Sharp
env = GTK_ICON_THEME,Kora           # Make sure this icon theme exists in /usr/share/icons or ~/.icons
env = XDG_CURRENT_DESKTOP,Hyprland
# optional: env = GDK_BACKEND,x11

# Qt Apps
env = QT_QPA_PLATFORMTHEME,qt5ct