input {
    kb_layout = fr
    # Set as needed
    kb_rules = 
    kb_variant =
    kb_model =

    follow_mouse = 1

    # Range is -1.0 to 1.0 | 0 means no modification to sensitivity.
    sensitivity = 0 

    touchpad {
        natural_scroll = false
    }
}