#source
source = $HOME/.config/hypr/configs/variables.conf

# mod + enter = start terminal
bind = $MainMod, Return, exec, $terminal
# mod + Q = kill current focused application
bind = $MainMod SHIFT, Q, killactive,
# mod + shift + S = take screenshot of area, MUST HAVE HYPRSHOT INSTALLED!
bind = $MainMod SHIFT, S, exec, hyprshot --mode region --output-folder /home/espadia/Images/
# mod + E = open file manager (I prefer caja).
bind = $MainMod, E, exec, $fileManager
# mod + shift + space = Toggle focused window to be floating or tiled.
bind = $MainMod SHIFT, SPACE, togglefloating
# mod + F = toggle focused window to full-screen view.
bind = $MainMod, F, fullscreen
# mod + D = toggle application launcher (I prefer wofi).
bind = $MainMod, SPACE, exec, $menu

#launch default applications
bind = $MainMod, D, exec, discord
bind = $MainMod, O, exec, $notes
bind = $MainMod, T, exec, $codeedit
bind = $MainMod, B, exec, $browser
bind = $MainMod, L, exec, hyprlock

# Switch current workspaces with mainMod + [0-9]
bind = $MainMod, ampersand, workspace, 1
bind = $MainMod, eacute, workspace, 2
bind = $MainMod, quotedbl, workspace, 3
bind = $MainMod, apostrophe, workspace, 4
bind = $MainMod, parenleft, workspace, 5
bind = $MainMod, minus, workspace, 6
bind = $MainMod, egrave, workspace, 7
bind = $MainMod, underscore, workspace, 8
bind = $MainMod, ccedilla, workspace, 9
bind = $MainMod, R, workspace, 10

# Move a focused window to a workspace with mainMod + SHIFT + [0-9]
bind = $MainMod SHIFT, ampersand, movetoworkspace, 1
bind = $MainMod SHIFT, eacute, movetoworkspace, 2
bind = $MainMod SHIFT, quotedbl, movetoworkspace, 3
bind = $MainMod SHIFT, apostrophe, movetoworkspace, 4
bind = $MainMod SHIFT, parenleft, movetoworkspace, 5
bind = $MainMod SHIFT, minus, movetoworkspace, 6
bind = $MainMod SHIFT, egrave, movetoworkspace, 7
bind = $MainMod SHIFT, underscore, movetoworkspace, 8
bind = $MainMod SHIFT, ccedilla, movetoworkspace, 9
bind = $MainMod SHIFT, R, movetoworkspace, 10

# Move and Resize windows with mainMod + LMB/RMB and dragging, drag on edges to resize.
bindm = $MainMod, mouse:272, movewindow
bindm = $MainMod, mouse:273, resizewindoz

#display workplace specific notifications using hyprctl
bind = $MainMod, ampersand, exec, hyprctl notify 2 1000 "rgb(008080)" "fontsize:10 DEV/CODE"
bind = $MainMod, eacute, exec, hyprctl notify 2 1000 "rgb(008080)" "fontsize:10 BROWSER"
bind = $MainMod, quotedbl, exec, hyprctl notify 2 1000 "rgb(008080)" "fontsize:10 STEAM"
bind = $MainMod, apostrophe, exec, hyprctl notify 2 1000 "rgb(008080)" "fontsize:10 GAMING"
bind = $MainMod, parenleft, exec, hyprctl notify 2 1000 "rgb(008080)" "fontsize:10 DISCORD"

#change wallpaper using awww and rofi script
bind = $MainMod, W, exec, bash $scripts/change-wp.sh
