#super key 
$Mod = SUPER

#default apps
$terminal = kitty
$fileManager = nautilus
$browser = zen-browser --disable-gpu
$menu = rofi -show drun
$codeedit = code-oss
$notes = obsidian --disable-gpu
$MainMod = SUPER

#directories
$scripts = $HOME/.config/hypr/scripts
$profile_pictures = $HOME/.config/hypr/images/avatars
