# WORKSPACE 1 - Code
windowrule = workspace 1, match:class ^(code-oss)$

# WORKSPACE 2 - Browser
windowrule = workspace 2, match:class ^(zen|brave-browser)$

# WORKSPACE 3 - Steam
# windowrule = workspace 3, tile on, match:class ^(steam)$
windowrule = workspace 3, match:class ^(heroic)$

# WORKSPACE 4 - Jeux
windowrule = workspace 4, fullscreen on, match:class ^(org.vinegarhq.Sober)$
windowrule = workspace 4, match:class ^(Minecraft)$

# WORKSPACE 5 - Discord
windowrule = workspace 5, match:class ^(discord)$

# WORKSPACE 6 - Music
windowrule = workspace 6, match:class ^(spotify)$